- ios/ContainerView.swift
- ios/DataCollectionView.swift
- ios/MasterColumnCollectionView.swift
- ios/PaddedLabel.swift
This is the start of freezing first column in iOS.  This just moves a few func's from DataCollectionView to a new super class MaterCollectionView.   DataCollectionView is now a base class.
> refactor: sproute master collection view class

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableImageView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Content.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomRecyclerView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataProvider.java
- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
Changes:
- Created CellView which composes of a Content (ClickableImageView, or ClickableTextView)
- Context menu with Copy (**No translations yet**)
- You can now copy the value of any cell
> feat(md-3365): copy cell android

- android/src/main/java/com/qliktrialreactnativestraighttable/CustomRecyclerView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowCountView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
Adds a position indicator to the bottom of the Table
> feat(md-3351): row count android

- android/src/main/java/com/qliktrialreactnativestraighttable/CellContentStyle.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableImageView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextWrapper.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ColumnWidths.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ConditionalTypeFaceSpan.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Content.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomLinearLayoutManger.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomRecyclerView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataColumn.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataProvider.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DragBox.java
- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderContentStyle.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Indicator.java
- android/src/main/java/com/qliktrialreactnativestraighttable/JsonUtils.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ReactNativeStraightTableViewManager.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Representation.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowCountView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableTheme.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TextWrapper.java
To test this the fontello fonts will need to be added to the TableApp and the latest of work/ongoing
1. get the fontello fonts
2. add the fontello.ttf  under `sn-table/react-native-dev/TableApp/android/app/src/main/assets/fonts`
> feat: android styling and conditionals

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableImageView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Content.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataProvider.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MiniChartView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ReactNativeStraightTableViewManager.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowCountView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
- src/components/SimpleGrid.tsx
Adds column totals which stick to the top or bottom of the table
> feat(md-3350): column totals android

- android/src/main/java/com/qliktrialreactnativestraighttable/DragBox.java
- android/src/main/java/com/qliktrialreactnativestraighttable/EventUtils.java
- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ReactNativeStraightTableViewManager.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowCountView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TotalsView.java
- src/atoms.ts
- src/components/SimpleGrid.tsx
Changes:
- Fixed totals cell resizing
- Dragbox improvements
- Added atom for qsm to detect if it is active
- hide on column resize
- z index fixes
> fix(md-3766): styling & dragbox

- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/SearchButton.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
Updated the sort indicator to be a top/bottom border instead of arrows.
> fix(md-3779): column sort indicators android

- android/src/main/java/com/qliktrialreactnativestraighttable/DataProvider.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
Totals need to be set before createAll is called.
> fix(md-3805): totals missing

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
> fix: alpha android

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/EventUtils.java
Adds all columns to the expand JSON
> fix(md-3843): fix expand row android

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableImageView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ColumnWidths.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Content.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataProvider.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataRow.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MiniChartView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ReactNativeStraightTableViewManager.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RootLayout.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TotalsViewCell.java
- src/components/ImageCell.tsx
Fixes several crashes & allows for column editing.
> fix(md-3832): edit table crash android

- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataColumn.java
- android/src/main/java/com/qliktrialreactnativestraighttable/qValue.java
- android/src/main/java/com/qliktrialreactnativestraighttable/qValues.java
Fixes issue where images and links were rendered as text in the expand view.
> fix(md-3843): expand row fixes

- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
Fixes an issue where styling was not applied if the column has an indicator set
> fix: background color when indicator set

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
My last PR broke selections, this fixes it
> fix: broken select

- android/src/main/java/com/qliktrialreactnativestraighttable/CustomHorizontalScrollView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomRecyclerView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataProvider.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DataRow.java
- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ImageLoader.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MiniChartViewManager.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MockHorizontalScrollView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MockVerticalScrollView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ReactNativeStraightTableViewManager.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowCountView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
Changes:
- Added vertical scrollbar, fixed horizontal scrollbar
- Created ImageLoader and moved logic out of dataProvider
- Removed cols and rows from manager
- Fixed row count zindex
> fix(md-3839): scrollbars and crash

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableTheme.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TextWrapper.java
Small fix for cell padding
Changes:
- Reduces padding to 8dp (to match ios)
- Fixes bug where the cell line calculation was using more than 2x the padding
> fix: use same cell padding

- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TotalsViewCell.java
Changes:
- Totals pick up content body color
- Fix potential crash when copying a cell
> fix(md-3895): totals should pickup color

- ios/DataCellView.swift
- ios/MiniBarChart.swift
- ios/MiniChartView.swift
- ios/MiniDotGraph.swift
- ios/MiniSparkLineChart.swift
- ios/PositiveNegativeChart.swift
- ios/ReactNativeMiniChartView.swift
- src/components/SimpleGrid.tsx
> fix: background color image views

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableImageView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
Changes:
- Swaps behaviour of alwaysFit and fitToHeight
- Fixes column/image resizing for full width sizing options
> fix(md-3924): image sizing

- .github/workflows/linting.yml
- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableImageView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ClickableTextView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomHorizontalScrollView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomRecyclerView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/DragBox.java
- android/src/main/java/com/qliktrialreactnativestraighttable/GrabberView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderCell.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MockHorizontalScrollView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RootLayout.java
- android/src/main/java/com/qliktrialreactnativestraighttable/RowCountView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/SearchButton.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableViewFactory.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TotalsView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TotalsViewCell.java
remove the use of @SuppressLint("ClickableViewAccessibility")
> ci: disable java lint when no changes detected

- android/src/main/java/com/qliktrialreactnativestraighttable/CellView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/ColumnWidths.java
- android/src/main/java/com/qliktrialreactnativestraighttable/CustomRecyclerView.java
- android/src/main/java/com/qliktrialreactnativestraighttable/HeaderContentStyle.java
- android/src/main/java/com/qliktrialreactnativestraighttable/Indicator.java
- android/src/main/java/com/qliktrialreactnativestraighttable/MiniChartInfo.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TableTheme.java
- android/src/main/java/com/qliktrialreactnativestraighttable/TotalsView.java
- example/TableApp/ios/Podfile.lock
- ios/ColumnWidths.swift
- ios/PaddedLabel.swift
> fix: check for nulls, ignore exceptions, and check for zero

- ios/ImageCell.swift
Removes old image views and ensures that images assigned to the current view is the same image that was downloaded.
Fixes the image caching.
Updates selected state when getting new data for image cells
> fix(QB-23425): ensure images do not repeat and image caching is used 

- .github/workflows/linting.yml
Signed-off-by: Johan Enell <johan.enell@qlik.com>
> chore(linting): update to SwiftLint action

- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
this PR included fixes for [QB-30077]( https://jira.qlikdev.com/browse/QB-30077)
Please find attached screenshot with android image issue fixes
> fix: QB-30077 image loading issue on android 

- android/src/main/java/com/qliktrialreactnativestraighttable/RowViewHolder.java
This PR is for fix [bug](https://jira.qlikdev.com/browse/QB-30077), it has fixes for missing argument
https://github.com/user-attachments/assets/222cb60c-c5ea-4b17-88ce-b5f845f34717
> fix: Image loading url issue, added missing argument
